#!/usr/bin/python3
#
# CS3700, Fall 2021
# TCP Project Starter Code

import datetime
import json
import sys
import socket
import time

from base64 import b64encode

# setting up default values
MSG_SIZE = 1500
DATA_SIZE = 1000
TIMEOUT = 30
SEQUENCE = 0
SENT_PACKETS = dict()
LAST_RECIEVED_TIME = None
RTT = 0.1

# Bind to localhost and port
IP_PORT = sys.argv[1]
UDP_IP = IP_PORT[0:IP_PORT.find(":")]
UDP_PORT = int(IP_PORT[IP_PORT.find(":")+1:])
dest = (UDP_IP, UDP_PORT)

time.sleep(.5)

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.settimeout(TIMEOUT)

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " 3700send: " + string + "\n")

def send_next_packet():
  global SEQUENCE
  global SENT_PACKETS
  global RTT

  # print(str(b64encode(data)))
  msg = {"sequence": SEQUENCE, "data": "", "ack": False, "eof": False}
  data = sys.stdin.buffer.read(DATA_SIZE - len(json.dumps(msg)))
  msg = json.dumps({"sequence": SEQUENCE, "data": b64encode(data).decode(), "ack": False, "eof": False})
  if (len(data) > 0):
    if sock.sendto(msg.encode(), dest) < len(msg):
      log("[error] unable to fully send packet")
    else:
      log("[send data] " + str(SEQUENCE) + " (" + str(len(data)) + ")")
      packet_send_time = time.time()
      packet_timeout = packet_send_time + (2 * RTT)
      SENT_PACKETS[SEQUENCE] = {
          "packet message": msg,
          "packet send time": packet_send_time,
          "packet timeout": packet_timeout,
          "packet retransmissions": 0
        }
      # log("len(SENT_PACKETS) " + str(len(SENT_PACKETS)))
      # log("SENT_PACKETS[SEQUENCE] " + str(SENT_PACKETS[SEQUENCE]))
      # log("SEQUENCE " + str(SEQUENCE))
    SEQUENCE += len(data)
    return True
  else:
    # dealing with EOF
    eof_msg = {"eof": True, "data": "", "sequence": SEQUENCE, "ack": False}
    if sock.sendto(json.dumps(eof_msg).encode(), dest) < len(eof_msg):
      log("[error] unable to fully send packet")
    else:
      log(f"[send data] {SEQUENCE} ({len(eof_msg)})")
      packet_send_time = time.time()
      packet_timeout = packet_send_time + (2 * RTT)
      SENT_PACKETS[SEQUENCE] = {
        "packet message": eof_msg,
        "packet send time": packet_send_time,
        "packet timeout": packet_timeout,
        "packet retransmissions": 0
      }
    sock.sendto(json.dumps(eof_msg).encode(), dest)
    return False

# Send first packet
send_next_packet()

# Now read in data, send packets
while True:
  log("ABOUT TO SLEEP")
  try:
      result = sock.recvfrom(MSG_SIZE)
  except socket.timeout:
      log("socket timedout")
      result = None
  
  if result:
    LAST_RECIEVED_TIME = time.time()
    (data, addr) = result
    try:
      decoded = json.loads(data.decode())
      log("[recv pkt] " + str(decoded))
      log("[recv ack] " + str(decoded['ack']))
      # log("SENT_PACKETS " + str(SENT_PACKETS))

      sack = decoded["sack"]
      if sack in SENT_PACKETS:
        sent_packet = SENT_PACKETS[sack]
        
        if sent_packet["packet retransmissions"] == 0:
          # Recompute RTT 
          packet_send_time = sent_packet["packet send time"]
          new_rtt = 0.875 * RTT + (1.0 - 0.875) * (time.time() - packet_send_time)
          RTT = new_rtt

        # packet was recieved
        del SENT_PACKETS[sack]

      unacked_seq_nums = list(SENT_PACKETS.keys())
      log("unacked_seq_nums " + str(unacked_seq_nums))
      for sequence_num in unacked_seq_nums: 
        if sequence_num < decoded["ack"]:
            del SENT_PACKETS[sequence_num]

      
      log("decoded[ACK] " + str(decoded["ack"]))
      log("SEQUENCE " + str(SEQUENCE))
      # if there is an ack try to send next packet
      if decoded["ack"] == SEQUENCE and not send_next_packet():
        break

    except (ValueError, KeyError, TypeError):
      log("[recv corrupt packet]")
  current_time = time.time()
  if ((current_time - LAST_RECIEVED_TIME) > (TIMEOUT * 1000)):
    log("[error] timeout")
    sys.exit(-1)
  else:
    log("len SENT_PACKETS " + str(len(SENT_PACKETS)))  
    for sequence_number in SENT_PACKETS:
        log ("sequence_number " + str(sequence_number))
        # re send packet if RTO expired
        sent_packet = SENT_PACKETS[sequence_number]
        if (current_time > sent_packet["packet timeout"]):
          # re sending packet
          packet = SENT_PACKETS[sequence_number]
          msg = packet["packet message"]
          if sock.sendto(json.dumps(msg).encode(), dest) < len(msg):
            log("[error] unable to fully send packet")
          else:
            log(f"[send data] {sequence_number} ({len(msg['data'])})")
            packet_send_time = time.time()
            packet_timeout = packet_send_time + 2 * RTT * (packet["packet retransmissions"] + 1)
            SENT_PACKETS[sequence_number] = {
              "packet message": msg,
              "packet send time": packet_send_time,
              "packet timeout": packet_timeout,
              "packet retransmissions": packet["packet retransmissions"] + 1
            }
sys.exit(0)
